# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: MVN clean single-headless Execute tests ${{inputs.APP_NAME}}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mvn clean test -Dkarate.options="--tags @AZ -T 5" -Dtest=ExamplesTest 
        shell: cmd
        timeout-minutes: 360
    - uses: deblockt/cucumber-report-annotations-action@v1.7
      if: always()
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/target/karate-reports/*.json"
        show-global-summary-report: true
    